# -*- coding: utf-8 -*-
"""TelecomX_LATAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_A4tubzpZfRQbUUGw1uVEru75ULzIkwb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#📌 Extracción"""

datos = pd.read_json('C:\Users\valem\Downloads\telecomx_latam.py')
datos.head(10)

datos.info()

datos.columns

"""#🔧 Transformación"""

datos.isnull().sum()

datos['customerID'].duplicated().sum()

"""#📊 Carga y análisis"""

customer = pd.json_normalize(datos['customer'])
phone = pd.json_normalize(datos['phone'])
internet = pd.json_normalize(datos['internet'])
account = pd.json_normalize(datos['account'])

datos_limpios = pd.concat(
    [datos[['customerID','Churn']], customer, phone, internet, account],
    axis=1
)

datos_limpios.head()

datos_limpios.isnull().sum()

datos_limpios["Charges.Total"] = pd.to_numeric(
    datos_limpios["Charges.Total"], errors="coerce"
)

datos_limpios["Churn"].value_counts()

datos_limpios.columns

datos_limpios["Cuentas_Diarias"] = datos_limpios["Charges.Monthly"] / 30

datos_limpios[["Charges.Monthly", "Cuentas_Diarias"]].head()

columnas_binarias = [
    "Partner","Dependents","PhoneService","PaperlessBilling",
    "OnlineSecurity","OnlineBackup","DeviceProtection",
    "TechSupport","StreamingTV","StreamingMovies"
]

for col in columnas_binarias:
    datos_limpios[col] = datos_limpios[col].map({"Yes":1, "No":0})

datos_limpios["Churn"] = datos_limpios["Churn"].map({"Yes":1, "No":0})

datos_limpios = datos_limpios.rename(columns={
    "Charges.Monthly": "Cargos_Mensuales",
    "Charges.Total": "Cargos_Totales",
    "tenure": "Antiguedad_Cliente"
})

datos_limpios.info()

datos_limpios.describe()

datos_limpios["Antiguedad_Cliente"].describe()

datos_limpios.describe()

churn_counts = datos_limpios["Churn"].dropna().value_counts()

plt.figure(figsize=(6,4))
plt.bar(["Permanecen","Cancelaron"], churn_counts)

plt.title("Distribución de Cancelación de Clientes")
plt.xlabel("Estado del Cliente")
plt.ylabel("Cantidad de Clientes")

plt.show()

churn_counts = datos_limpios["Churn"].dropna().value_counts()

plt.figure(figsize=(6,6))
plt.pie(churn_counts, labels=["Permanecen","Cancelaron"], autopct="%1.1f%%")

plt.title("Proporción de Cancelación de Clientes")

plt.show()

tabla_genero = pd.crosstab(datos_limpios["gender"], datos_limpios["Churn"])

tabla_genero.plot(kind="bar", figsize=(6,4))

plt.title("Cancelación de Clientes por Género")
plt.xlabel("Género")
plt.ylabel("Cantidad de Clientes")

plt.show()

tabla_contrato = pd.crosstab(datos_limpios["Contract"], datos_limpios["Churn"])

tabla_contrato.plot(kind="bar", figsize=(7,4))

plt.title("Cancelación de Clientes por Tipo de Contrato")
plt.xlabel("Tipo de Contrato")
plt.ylabel("Cantidad de Clientes")

plt.show()

tabla_pago = pd.crosstab(datos_limpios["PaymentMethod"], datos_limpios["Churn"])

tabla_pago.plot(kind="bar", figsize=(8,4))

plt.title("Cancelación de Clientes por Método de Pago")
plt.xlabel("Método de Pago")
plt.ylabel("Cantidad de Clientes")

plt.xticks(rotation=45)

plt.show()

tabla_internet = pd.crosstab(datos_limpios["InternetService"], datos_limpios["Churn"])

tabla_internet.plot(kind="bar", figsize=(6,4))

plt.title("Cancelación de Clientes por Tipo de Internet")
plt.xlabel("Tipo de Servicio de Internet")
plt.ylabel("Cantidad de Clientes")

plt.show()

plt.figure(figsize=(6,4))

datos_limpios.boxplot(column="Antiguedad_Cliente", by="Churn")

plt.title("Antigüedad del Cliente vs Cancelación")
plt.suptitle("")
plt.xlabel("Cancelación (0 = Permanece, 1 = Canceló)")
plt.ylabel("Meses como Cliente")

plt.show()

plt.figure(figsize=(6,4))

datos_limpios.boxplot(column="Cargos_Mensuales", by="Churn")

plt.title("Cargos Mensuales vs Cancelación")
plt.suptitle("")
plt.xlabel("Cancelación (0 = Permanece, 1 = Canceló)")
plt.ylabel("Cargos Mensuales")

plt.show()

plt.figure(figsize=(6,4))

datos_limpios.boxplot(column="Cargos_Totales", by="Churn")

plt.title("Cargos Totales vs Cancelación")
plt.suptitle("")
plt.xlabel("Cancelación (0 = Permanece, 1 = Canceló)")
plt.ylabel("Total Gastado")

plt.show()

plt.figure(figsize=(6,4))

datos_limpios.boxplot(column="Cuentas_Diarias", by="Churn")

plt.title("Gasto Diario vs Cancelación")
plt.suptitle("")
plt.xlabel("Cancelación (0 = Permanece, 1 = Canceló)")
plt.ylabel("Gasto Diario")

plt.show()







"""#📄Informe final"""

